# Generated by Django 5.2.3 on 2025-06-18 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_users_is_first_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='mobile',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
