# Generated by Django 5.2.3 on 2025-06-19 12:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_users_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='mobile',
            field=models.CharField(default=9976594960, max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid 10-digit Indian mobile number starting with 6, 7, 8, or 9.', regex='^[6-9]\\d{9}$')]),
            preserve_default=False,
        ),
    ]
